version: '3.3'

services:
  db:
    container_name: pgsql_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: astro
    ports:
      - "5432:5432"
    networks:
      static:
        ipv4_address: 192.168.25.10
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      static:
        ipv4_address: 192.168.25.20
    depends_on:
      - db
    volumes:
      - '/var/lib/pgadmin/storage:/home/jason/docker/pgadmin/storage'

# set up a static IP address block so that I don't have to play Columbo to
# find the IP address of the db server (HOW'S THAT FOR AN OLD REFERENCE HUH?)
networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.25.0/16
          #gateway: 192.168.25.1